version: "3.9"
services:
  web:
    build: 
        context: .
        dockerfile: Dockerfile 
    restart: unless-stopped
    ports:
      - target: 8000
        published: 9157
    volumes:
      - ${PWD}/CONFIG.yml:/CONFIG.yml
    healthcheck:
      test: python3 healthcheck.py
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 15s

